#!/bin/sh

echo "rm -rf ~/devel/driver/iwlwifi-stack-dev/iperf_test"
rm -rf ~/devel/driver/iwlwifi-stack-dev/iperf_test
echo "mkdir ~/devel/driver/iwlwifi-stack-dev/iperf_test"
mkdir ~/devel/driver/iwlwifi-stack-dev/iperf_test


for i in `seq 1 $2`
do
	echo "##############test num $i##########################"

	# ---------------- setup client side ------------------------- #
	echo ">> sudo killall wpa_supplicant"
	sudo killall wpa_supplicant
	echo ">> sudo modprobe iwlmvm -r"
	sudo modprobe iwlmvm -r
	echo ">> sudo modprobe iwlwifi -r"
	sudo modprobe iwlwifi -r

	echo "sudo dmesg -c &"
	sudo dmesg -c &

	echo ">> sudo modprobe iwlwifi debug=0x00100000"
	sudo modprobe iwlwifi debug=0x00100000
	sleep 3
	echo ">> sudo ifconfig wlan0 up"
	sudo ifconfig wlan0 up

#	echo ">> sudo wpa_supplicant -i wlan0 -c /usr/share/ix/script/test/wifi/sta_11i/DEV-OPEN-GN.conf -B"
	echo "sudo wpa_supplicant -i wlan0 -c ~/bin/suppConfFiles/$1.conf -B"
	sudo wpa_supplicant -i wlan0 -c ~/bin/suppConfFiles/$1.conf -B
#	sudo wpa_supplicant -i wlan0 -c /usr/share/ix/script/test/wifi/sta_11i/DEV-OPEN-GN.conf -B
	sleep 5

	#echo "sudo dhclient wlan0"
	#sudo dhclient wlan0
	echo "sudo ifconfig wlan0 10.10.10.01"
	sudo ifconfig wlan0 10.10.10.01
#	echo "sudo dhclient wlan0 -r"
#	sudo dhclient wlan0 -r
#	echo "sudo dhclient wlan0"
#	sudo dhclient wlan0

	sleep 3

	# ---------------- setup server side ------------------------- #
	echo ">> adb kill-server"
	adb kill-server
	sleep 3

	echo ">> adb connect 10.12.217.135"
	adb connect 10.12.217.135

	echo "adb shell dmesg -c &"
	adb shell dmesg -c &

	adb shell lsmod | grep iwl

	echo ">> adb shell am startservice --user 0 -a android.intent.action.run -n com.intel.mwg/com.intel.Dispatcher -e ITE_METHOD DUT.WiFi.EnableDevice"
	adb shell am startservice --user 0 -a android.intent.action.run -n com.intel.mwg/com.intel.Dispatcher -e ITE_METHOD DUT.WiFi.EnableDevice
	sleep 5

	echo "adb shell am startservice --user 0 -a android.intent.action.run -n com.intel.mwg/com.intel.Dispatcher -e ITE_METHOD DUT.WiFiProfile.DeleteAllProfiles"
	adb shell am startservice --user 0 -a android.intent.action.run -n com.intel.mwg/com.intel.Dispatcher -e ITE_METHOD DUT.WiFiProfile.DeleteAllProfiles


	echo "adb shell am startservice --user 0 -a android.intent.action.run -n com.intel.mwg/com.intel.Dispatcher -e ITE_METHOD DUT.WiFiProfile.CreateProfile -e ARG SSID:$1 ,PASSWORD:none,SECURITY:Open.Personal.None"
	adb shell am startservice --user 0 -a android.intent.action.run -n com.intel.mwg/com.intel.Dispatcher -e ITE_METHOD DUT.WiFiProfile.CreateProfile -e ARG SSID:$1,PASSWORD:none,SECURITY:Open.Personal.None
	sleep 1

	echo "adb shell am startservice --user 0 -a android.intent.action.run -n com.intel.mwg/com.intel.Dispatcher -e ITE_METHOD DUT.WiFiProfile.ConnectProfile -e ARG SSID:$1"
	adb shell am startservice --user 0 -a android.intent.action.run -n com.intel.mwg/com.intel.Dispatcher -e ITE_METHOD DUT.WiFiProfile.ConnectProfile -e ARG SSID:$1
	sleep 5
	
#	c=`adb shell netcfg | grep wlan0 | awk '{print $3}'`
#	ip=${c%%/*}
#	echo "got ip for Android PC $ip"

	echo "adb shell ifconfig wlan0 10.10.10.02"
	adb shell ifconfig wlan0 10.10.10.02
	ip=`10.10.10.01`

	echo "iperf -s -u -w 64K -p 5111 -l 1370 -P 1 -i 1 -f m -S 0 > ~/devel/driver/iwlwifi-stack-dev/iperf_test/ipref_s_$i 2>&1 & echo $!"
	iperf -s -u -w 64K -p 5111 -l 1370 -P 1 -i 1 -f m -S 0 > ~/devel/driver/iwlwifi-stack-dev/iperf_test/ipref_s_$i 2>&1 & echo $!
	
	echo "adb shell iperf -c $ip -u -b 1M -t 60 -w 64K -p 5111 -l 1370 -P 1 -i 1 -f m -S 0 > ~/devel/driver/iwlwifi-stack-dev/iperf_test/ipref_$i 2>&1 & echo $!"
	adb shell iperf -c $ip -u -b 1M -t 60 -w 64K -p 5111 -l 1370 -P 1 -i 1 -f m -S 0 > ~/devel/driver/iwlwifi-stack-dev/iperf_test/ipref_$i 2>&1 & echo $!

#	echo "adb shell iperf -s -u -w 64K -p 5111 -l 1370 -P 1 -i 1 -f m -S 0 > ~/devel/driver/iwlwifi-stack-dev/iperf_test/ipref_s_$i 2>&1 & echo $!"
#	adb shell iperf -s -u -w 64K -p 5111 -l 1370 -P 1 -i 1 -f m -S 0 > ~/devel/driver/iwlwifi-stack-dev/iperf_test/ipref_s_$i 2>&1 & echo $!
	
#	echo "iperf -c $ip -u -b 1M -t 60 -w 64K -p 5111 -l 1370 -P 1 -i 1 -f m -S 0 > ~/devel/driver/iwlwifi-stack-dev/iperf_test/ipref_$i 2>&1 & echo $!"
#	iperf -c $ip -u -b 1M -t 60 -w 64K -p 5111 -l 1370 -P 1 -i 1 -f	m -S 0 > ~/devel/driver/iwlwifi-stack-dev/iperf_test/ipref_$i 2>&1 & echo $!

### TCP ####
	#echo "adb shell iperf -s -w 128K -p 5124 -l 1370 -P 1 -i 1 -f m -S 0 > ~/devel/driver/iwlwifi-stack-dev/iperf_test/ipref_s_$i 2>&1 & echo $!"
	#adb shell iperf -s -w 128K -p 5124 -l 1370 -P 1 -i 1 -f m -S 0  > ~/devel/driver/iwlwifi-stack-dev/iperf_test/ipref_s_$i 2>&1 & echo $!

	#echo "iperf -c $ip -t 30 -w 128K -p 5124 -l 1370 -P 1 -i 1 -f m -S 0 > ~/devel/driver/iwlwifi-stack-dev/iperf_test/ipref_$i 2>&1 & echo $!"
	#iperf -c $ip -t 30 -w 128K -p 5124 -l 1370 -P 1 -i 1 -f m -S 0 > ~/devel/driver/iwlwifi-stack-dev/iperf_test/ipref_$i 2>&1 & echo $!

	sleep 62
	echo ">> adb shell am startservice --user 0 -a android.intent.action.run -n com.intel.mwg/com.intel.Dispatcher -e ITE_METHOD DUT.WiFi.DisableDevice"
	adb shell am startservice --user 0 -a android.intent.action.run -n com.intel.mwg/com.intel.Dispatcher -e ITE_METHOD DUT.WiFi.DisableDevice

	dmesg > ~/devel/driver/iwlwifi-stack-dev/iperf_test/dmesg_$i
	adb shell dmesg > ~/devel/driver/iwlwifi-stack-dev/iperf_test/adb_dmesg_$i
	
	adb shell lsmod | grep iwl
done
