#!/bin/sh
sudo killall wpa_supplicant
echo "=== Supplicant killed ==="
#sudo modprobe -r iwlmvm
#echo "=== Removed Driver =="
#sleep 1
#sudo modprobe iwlwifi
#echo "=== Driver Loaded ==="
sleep 2
sudo wpa_supplicant -T -s -iwlan0 -c ~/bin/suppConfFiles/Avi-WPAN1-a.conf -m ~/bin/wpa_supplicant_p2p.conf -B -d -D nl80211 -g /tmp/wpa_supplicat –G adm 
#sudo wpa_supplicant -T -s -iwlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf -m ~/bin/wpa_supplicant_p2p.conf -B -d -Dnl80211

#sudo wpa_supplicant -T -s -i wlan0 -c  ~/bin/wpa_supplicant_p2p.conf -B -dd -Dnl80211
#sudo wpa_supplicant -i wlan0 -c  ~/bin/wpa_supplicant_p2p.conf -B -d -Dnl80211
#sudo iw dev wlan0 connect -w "DEV-OPEN-GN"

#sleep 4
#sudo dhclient wlan0
#sleep 4
echo "Done."
sudo wpa_cli -i p2p0 -g /tmp/wpa_supplicat -G adm
