#!/bin/bash -x

sudo atp-get update

sudo apt-get install gitk -y
sudo apt-get install git-gui -y
sudo apt-get install terminator -y

sudo apt-get install python-dev swig -y
sudo apt-get install sshpass -y

sudo apt-get install libswitch-perl -y
sudo apt-get install libperl -y
