#! /bin/bash


PATCH_FILE=$(git format-patch -1)
~/devel/zephyr/wcd_rtos-zephyr/scripts/checkpatch.pl --no-tree --ignore=BLOCK_COMMENT_STYLE --ignore=NETWORKING_BLOCK_COMMENT_STYLE $PATCH_FILE

rm $PATCH_FILE
